# Generated by Django 5.1.2 on 2024-10-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_chat_historial_remove_chat_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', through='tienda.ProductoCategoria', to='tienda.categoria'),
        ),
    ]
