# Generated by Django 5.1.2 on 2024-10-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_compra_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproducto',
            name='cantidad',
        ),
    ]
