# Generated by Django 5.1.2 on 2024-10-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_compraproducto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproducto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='compraproducto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='compraproducto',
            name='subtotal',
        ),
    ]
