# Generated by Django 5.1.2 on 2024-10-31 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_compraproducto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
    ]
